In [5]:
# numpy's main object is the multidimensional array

# it is a table of elements, all of the same type, indexed by a tuple of positive integers
# in numpy arrays dimensions are called axes . the no of axes is called the rank
# A tuple of integers giving the size of each dim is known as shape of the array
# numpy's array class is called ndarray. it is also known as alias array

1


In [2]:
import numpy as np

# creating array object from lists

myarr = np.array([[1,2,3],[4,5,6]])


#creating an array obecrt using only zeros

myarr1 = np.zeros((3,3), dtype = int)
print(myarr1)

# Printing type of array object 
print(type(myarr))

#printing dimension
print(myarr.ndim)

# printing the shape
print(myarr.shape)

# printing the size
print(myarr.size)

# printing type of elements in array
print(myarr.dtype)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>
2
(2, 3)
6
int32


In [1]:
# Accessing the array index


import numpy as np
arr = np.array([[-1, 2, 0, 4],
                [4,5,6,7],
                [1,2,3,4],
                [4,5,6,7]])
print(arr)

# printing a range of array using slicing method

sliced_arr = arr[:2, ::2]
print(sliced_arr)


#printing specific elements
indexed_arr = arr[[1,2,3,3], [1,2,0,1]]
print(indexed_arr)



[[-1  2  0  4]
 [ 4  5  6  7]
 [ 1  2  3  4]
 [ 4  5  6  7]]
[[-1  0]
 [ 4  6]]
[5 3 4 5]


In [4]:

print("Harshdeep Singh Plaha 20MIC0005")
n, m = list(map(int, input().split()))
d = {}
for i in range(n):
    dict_name = input("")
    d[dict_name] = {}
    for i in range(m):
        player_name, score = input().split()
        d[dict_name][player_name] = int(score)
print(d)


def Max_Score(m):
    total = {}
    for i in m.keys():
        for n in m[i].keys():
            if n in total.keys():
                total[n] = total[n] + m[i][n]
            else:
                total[n] = m[i][n]
    print("Total Run Scored by Each Playes in 2 Tests: ")
    print(total)
    print("Player With highest score")
    max_total = -1
    for n in total.keys():
        if total[n] > max_total:
            max_name = n
            max_total = total[n]
    return (max_name, max_total)


match_summary = Max_Score(d)
print(match_summary)


Harshdeep Singh Plaha 20MIC0005
{'test1': {'dhoni': 89, 'kholi': 67}, 'test2': {'dhoni': 78, 'Rohit': 45}}
Total Run Scored by Each Playes in 2 Tests: 
{'dhoni': 167, 'kholi': 67, 'Rohit': 45}
Player With highest score
('dhoni', 167)
