In [5]:
# numpy's main objct is the multidimensional array

# it is a table of elements, all of the same type, indexed by a tuple of positive integers
# in numpy arrays dimensions are called axes . the no of axes is called the rank
# A tuple of integers giving the size of each dim is known as shape of the array
# numpy's array class is called ndarray. it is also known as alias array

1


In [1]:
import numpy as np

# creating array object
myarr = np.array([[1,2,3],[4,5,6]])

# Printing type of array object 
print(type(myarr))

#printing dimension
print(myarr.ndim)

# printing the shape
print(myarr.shape)

# printing the size
print(myarr.size)

# printing type of elements in array
print(myarr.dtype)

<class 'numpy.ndarray'>
2
(2, 3)
6
int32


In [1]:
# Accessing the array index


import numpy as np
arr = np.array([[-1, 2, 0, 4], [4,5,6,7],[1,2,3,4], [4,5,6,7]])
print(arr)

# printing a range of array using slicing method

sliced_arr = arr[:2, ::2]
print(sliced_arr)


#printing specific elements
indexed_arr = arr[[1,2,3,3], [1,2,0,1]]
print(indexed_arr)



[[-1  2  0  4]
 [ 4  5  6  7]
 [ 1  2  3  4]
 [ 4  5  6  7]]
[[-1  0]
 [ 4  6]]
[5 3 4 5]


In [ ]:
# Basic array operations


import numpy as np

